### ISSUE TITLE
 erlang error: :enoent on Windows

### ISSUE THREAD

**Issue by stanonyime** [route/mogrify#2]
I'm getting an  'enoent' on windows when I try the example code

**Comment by route** [comment]
Hm I haven't tried it on windows at all, my bad. Any stack trace?

**Comment by stanonyime** [comment]
It seems the cmd/2 system call does not work well on Windows.

**Comment by tomjoro** [comment]
You should try running just "mogrify" from Windows shell. The 'enoent' error is also returned when the executable is not able to run directly from the shell.

**Comment by route** [comment]
Thanks @tomjoro unfortunately (or fortunately) I don't have Windows.

**Comment by KamilZielinski** [comment]
I had the same issue, this lib doesn't work on Windows due to how it calls cmd (albo you always need to call `magick` on Windows which is missing in this lib. Unfortunately I don't feel fluent enough with Elixir to create PR.
In my case I had to call `cmd.exe` first with `/c` parameter so the rest of commands could be executed and I could get a return (without `/c` it's just stucked, see - [StackOverflow](https://stackoverflow.com/questions/49164534/elixir-system-cmd-isnt-working)
```
System.cmd("cmd.exe", ["/c", "magick", "mogrify", "-resize", "353x98", "-write", "C:/Users/Kamil/Downloads/star.jpg", "C:/Users/Kamil/Downloads/star.jpg"], [stderr_to_stdout: true])
# => {"", 0}
```
