### ISSUE TITLE
Custom to Run Composite

### ISSUE THREAD

**Issue by shawnbro** [route/mogrify#39]
I'm wondering if it's possible to run the `composite` command? (as specified here: http://www.imagemagick.org/Usage/layers/) with this wrapper.

**Comment by talklittle** [comment]
No, this library does not support the `composite` command currently.

You could try the [Composite Operator of Convert](https://www.imagemagick.org/Usage/layers/#convert) with `Mogrify.create/2` which calls `convert`. (Unlike `Mogrify.save/2` which calls `mogrify`.)

**Comment by shawnbro** [comment]
@talklittle would this work if I want to create a new image which is a combination of a few other images?

**Comment by talklittle** [comment]
@shawnbro It sounds like it would work. But I haven't tried it before. If you do try it out, please report back on whether it worked for you.

You can probably do `image = Mogrify.custom(image, "composite")` to add the `-composite` operator to the list of operators. Might have to do some extra fussing around with it though, because from ImageMagick documentation it looks like ImageMagick uses slightly different syntax to do `convert -composite` commands.

**Comment by shawnbro** [comment]
I ended up doing this:

```
image_operator(image, "convert -size:  wid #{image_path} \ #{image_to_combine_path}  -geometry  +0+10  -composite") 
|> create(in_place: true)
```

which merges `image_to_combine_path` image into `image_path` image.
