### ISSUE TITLE
does this library support "append" method?

### ISSUE THREAD

**Issue by gazoon** [route/mogrify#50]
I need to concatenate two images, can i do it with this library?

**Comment by talklittle** [comment]
Do you have the equivalent `mogrify` command-line command to demonstrate exactly what you are looking for?

**Comment by gazoon** [comment]
Yes, sure. I need this: 
`convert +append left_input_image.jpeg right_input_image.jpeg result_image.jpeg`
result_image.jpeg contains left_input_image.jpeg+right_input_image.jpeg

**Comment by talklittle** [comment]
Hmm this library doesn't yet support multiple input images, nor have very good support for `convert` syntax in general (it's primarily for `mogrify` right now).

Your best bet is probably to use `System.cmd`, otherwise pull requests are welcome if you can think of a nice API to add the needed functionality to this library.

**Comment by gazoon** [comment]
Ok, thx, i will use System.cmd
